//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIDAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbiDaoContainer : DbContext
    {
        public AbiDaoContainer()
            : base("name=AbiDaoContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collaborateur> CollaborateurSet { get; set; }
        public virtual DbSet<Contrat> ContratSet { get; set; }
        public virtual DbSet<AugmentationSalaire> AugmentationSalaireSet { get; set; }
        public virtual DbSet<Avenant> AvenantSet { get; set; }
    }
}
