//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AugmentationSalaire
    {
        internal System.DateTime Date { get; set; }
        internal decimal Augmentation { get; set; }
        internal int IdAugmentation { get; set; }
    
        public virtual Collaborateur Collaborateur { get; set; }
    }
}
