//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collaborateur()
        {
            this.Contrat = new HashSet<Contrat>();
            this.AugmentationSalaire = new HashSet<AugmentationSalaire>();
        }
    
        internal int Matricule { get; set; }
        internal string NomCollabo { get; set; }
        internal string PrenomCollabo { get; set; }
        public string FonctionCollabo { get; set; }
        internal string Adresse { get; set; }
        internal string Statut { get; set; }
        internal string Photo { get; set; }
        internal string SituationFamiliale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrat> Contrat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AugmentationSalaire> AugmentationSalaire { get; set; }
    }
}
