//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage : ContratTemporaire
    {
        internal string Ecole { get; set; }
        internal string Mission { get; set; }
        internal Nullable<decimal> Indemnite { get; set; }
    }
}
